// Generated by tools/optimize-images.py — do not edit by hand.
// Widths of the -800, -1200 and -1600 WebP variants for each bundled photo.
export const IMAGE_WIDTHS: Record<string, [number, number, number]> = {
  "/images/portfolio/about-1.jpg": [
    800,
    1198,
    1198
  ],
  "/images/portfolio/about-2.jpg": [
    800,
    1200,
    1200
  ],
  "/images/portfolio/about-3.jpg": [
    800,
    1200,
    1200
  ],
  "/images/portfolio/about-4.jpg": [
    800,
    1198,
    1198
  ],
  "/images/portfolio/about-5.jpg": [
    800,
    1200,
    1200
  ],
  "/images/portfolio/about-portrait.jpg": [
    800,
    1198,
    1198
  ],
  "/images/portfolio/about-story.jpg": [
    800,
    1200,
    1600
  ],
  "/images/portfolio/baby-2.jpg": [
    800,
    1200,
    1600
  ],
  "/images/portfolio/baby-3.jpg": [
    800,
    1200,
    1200
  ],
  "/images/portfolio/baby-clara-1.jpg": [
    800,
    1200,
    1600
  ],
  "/images/portfolio/baby-clara-2.jpg": [
    800,
    1200,
    1200
  ],
  "/images/portfolio/baby-clara-3.jpg": [
    800,
    1200,
    1600
  ],
  "/images/portfolio/baby-clara-4.jpg": [
    800,
    1200,
    1200
  ],
  "/images/portfolio/baby-clara-5.jpg": [
    800,
    1200,
    1600
  ],
  "/images/portfolio/baby-daryna-1.jpg": [
    800,
    1200,
    1600
  ],
  "/images/portfolio/baby-daryna-2.jpg": [
    800,
    1200,
    1200
  ],
  "/images/portfolio/baby-eva-1.jpg": [
    800,
    1200,
    1600
  ],
  "/images/portfolio/baby-eva-2.jpg": [
    800,
    1200,
    1600
  ],
  "/images/portfolio/baby-eva-3.jpg": [
    800,
    1200,
    1600
  ],
  "/images/portfolio/baby-featured.jpg": [
    800,
    1200,
    1600
  ],
  "/images/portfolio/baby-laura.jpg": [
    800,
    1200,
    1600
  ],
  "/images/portfolio/baby-madalena-1.jpg": [
    800,
    1200,
    1200
  ],
  "/images/portfolio/baby-madalena-2.jpg": [
    800,
    1200,
    1600
  ],
  "/images/portfolio/baby-margarida-1.jpg": [
    800,
    1200,
    1600
  ],
  "/images/portfolio/baby-margarida-2.jpg": [
    800,
    1200,
    1600
  ],
  "/images/portfolio/baby-nazar-2.jpg": [
    800,
    1200,
    1200
  ],
  "/images/portfolio/baby-nazar-3.jpg": [
    800,
    1200,
    1600
  ],
  "/images/portfolio/baby-nazar-4.jpg": [
    800,
    1200,
    1200
  ],
  "/images/portfolio/baby-nazar.jpg": [
    800,
    1200,
    1600
  ],
  "/images/portfolio/family-2022-1.jpg": [
    800,
    1200,
    1600
  ],
  "/images/portfolio/family-2022-2.jpg": [
    800,
    1200,
    1200
  ],
  "/images/portfolio/family-2022-3.jpg": [
    800,
    1200,
    1200
  ],
  "/images/portfolio/family-2023-2.jpg": [
    800,
    1200,
    1600
  ],
  "/images/portfolio/family-2023-3.jpg": [
    800,
    1200,
    1200
  ],
  "/images/portfolio/family-2023.jpg": [
    800,
    1200,
    1600
  ],
  "/images/portfolio/family-a.jpg": [
    800,
    1200,
    1200
  ],
  "/images/portfolio/family-andreia-1.jpg": [
    800,
    1200,
    1600
  ],
  "/images/portfolio/family-andreia-2.jpg": [
    800,
    1200,
    1200
  ],
  "/images/portfolio/family-b.jpg": [
    800,
    1200,
    1600
  ],
  "/images/portfolio/family-c.jpg": [
    800,
    1200,
    1600
  ],
  "/images/portfolio/family-d.jpg": [
    800,
    1200,
    1600
  ],
  "/images/portfolio/family-e.jpg": [
    800,
    1200,
    1600
  ],
  "/images/portfolio/family-f.jpg": [
    800,
    1200,
    1200
  ],
  "/images/portfolio/family-g.jpg": [
    800,
    1200,
    1600
  ],
  "/images/portfolio/family-h.jpg": [
    800,
    1200,
    1600
  ],
  "/images/portfolio/family-nazar-1.jpg": [
    800,
    1200,
    1200
  ],
  "/images/portfolio/family-nazar-2.jpg": [
    800,
    1200,
    1200
  ],
  "/images/portfolio/family-nazar-3.jpg": [
    800,
    1200,
    1200
  ],
  "/images/portfolio/family-patrick-1.jpg": [
    800,
    1200,
    1600
  ],
  "/images/portfolio/family-patrick-2.jpg": [
    800,
    1200,
    1200
  ],
  "/images/portfolio/family-patrick-3.jpg": [
    800,
    1200,
    1600
  ],
  "/images/portfolio/family-patrick-4.jpg": [
    800,
    1200,
    1600
  ],
  "/images/portfolio/family-patrick-5.jpg": [
    800,
    1200,
    1600
  ],
  "/images/portfolio/family-vanessa-1.jpg": [
    800,
    1200,
    1600
  ],
  "/images/portfolio/family-vanessa-2.jpg": [
    800,
    1200,
    1600
  ],
  "/images/portfolio/family-vanessa-3.jpg": [
    800,
    1200,
    1600
  ],
  "/images/portfolio/family-vanessa-4.jpg": [
    800,
    1200,
    1600
  ],
  "/images/portfolio/home-1.jpg": [
    800,
    1200,
    1600
  ],
  "/images/portfolio/home-2.jpg": [
    800,
    1200,
    1600
  ],
  "/images/portfolio/home-3.jpg": [
    800,
    1200,
    1600
  ],
  "/images/portfolio/home-daryna.jpg": [
    800,
    1200,
    1600
  ],
  "/images/portfolio/maternity-1.jpg": [
    800,
    1200,
    1600
  ],
  "/images/portfolio/maternity-2.jpg": [
    800,
    1200,
    1600
  ],
  "/images/portfolio/maternity-3.jpg": [
    800,
    1200,
    1200
  ],
  "/images/portfolio/maternity-afonso-1.jpg": [
    800,
    1200,
    1600
  ],
  "/images/portfolio/maternity-afonso-2.jpg": [
    800,
    1200,
    1600
  ],
  "/images/portfolio/maternity-alexandre.jpg": [
    800,
    1200,
    1200
  ],
  "/images/portfolio/maternity-camila.jpg": [
    800,
    1200,
    1200
  ],
  "/images/portfolio/maternity-duarte-2.jpg": [
    800,
    1200,
    1200
  ],
  "/images/portfolio/maternity-duarte-3.jpg": [
    800,
    1200,
    1200
  ],
  "/images/portfolio/maternity-duarte-4.jpg": [
    800,
    1200,
    1200
  ],
  "/images/portfolio/maternity-duarte-5.jpg": [
    800,
    1200,
    1600
  ],
  "/images/portfolio/maternity-duarte.jpg": [
    800,
    1200,
    1600
  ],
  "/images/portfolio/maternity-estudio-bw.jpg": [
    800,
    1200,
    1600
  ],
  "/images/portfolio/maternity-matias-1.jpg": [
    800,
    1200,
    1600
  ],
  "/images/portfolio/maternity-matias-2.jpg": [
    800,
    1200,
    1600
  ],
  "/images/portfolio/maternity-matias-3.jpg": [
    800,
    1200,
    1600
  ],
  "/images/portfolio/maternity-patricia.jpg": [
    800,
    1200,
    1600
  ],
  "/images/portfolio/maternity-praia-1.jpg": [
    800,
    1200,
    1600
  ],
  "/images/portfolio/maternity-praia-2.jpg": [
    800,
    1200,
    1200
  ],
  "/images/portfolio/maternity-praia-3.jpg": [
    800,
    1200,
    1600
  ],
  "/images/portfolio/maternity-vasco.jpg": [
    800,
    1200,
    1200
  ],
  "/images/portfolio/maternity-vicente-1.jpg": [
    800,
    1200,
    1600
  ],
  "/images/portfolio/maternity-vicente-2.jpg": [
    800,
    1200,
    1600
  ],
  "/images/portfolio/maternity-vicente-3.jpg": [
    800,
    1200,
    1200
  ],
  "/images/portfolio/newborn-1.jpg": [
    800,
    1200,
    1600
  ],
  "/images/portfolio/newborn-2.jpg": [
    800,
    1200,
    1600
  ],
  "/images/portfolio/newborn-3.jpg": [
    800,
    1200,
    1600
  ],
  "/images/portfolio/newborn-alexandre-1.jpg": [
    800,
    1200,
    1200
  ],
  "/images/portfolio/newborn-alexandre-2.jpg": [
    800,
    1200,
    1600
  ],
  "/images/portfolio/newborn-camila.jpg": [
    800,
    1200,
    1600
  ],
  "/images/portfolio/newborn-destaque.jpg": [
    800,
    1200,
    1600
  ],
  "/images/portfolio/newborn-eduardo.jpg": [
    800,
    1200,
    1600
  ],
  "/images/portfolio/newborn-eva.jpg": [
    800,
    1200,
    1200
  ],
  "/images/portfolio/newborn-featured.jpg": [
    800,
    1200,
    1600
  ],
  "/images/portfolio/newborn-frederica.jpg": [
    800,
    1200,
    1600
  ],
  "/images/portfolio/newborn-jovi.jpg": [
    800,
    1200,
    1600
  ],
  "/images/portfolio/newborn-leticia.jpg": [
    800,
    1200,
    1600
  ],
  "/images/portfolio/newborn-mariana-1.jpg": [
    800,
    1200,
    1600
  ],
  "/images/portfolio/newborn-mariana-2.jpg": [
    800,
    1200,
    1200
  ],
  "/images/portfolio/newborn-martina-mafalda-2.jpg": [
    800,
    1200,
    1600
  ],
  "/images/portfolio/newborn-martina-mafalda.jpg": [
    800,
    1200,
    1600
  ],
  "/images/portfolio/newborn-matias.jpg": [
    800,
    1200,
    1600
  ],
  "/images/portfolio/newborn-olivia.jpg": [
    800,
    1200,
    1600
  ],
  "/images/portfolio/newborn-simao.jpg": [
    800,
    1200,
    1200
  ],
  "/images/portfolio/newborn-vasco-1.jpg": [
    800,
    1200,
    1600
  ],
  "/images/portfolio/newborn-vasco-2.jpg": [
    800,
    1200,
    1600
  ],
  "/images/portfolio/newborn-vasco-3.jpg": [
    800,
    1200,
    1600
  ],
  "/images/portfolio/smash-1.jpg": [
    800,
    1200,
    1200
  ],
  "/images/portfolio/smash-3.jpg": [
    800,
    1200,
    1600
  ],
  "/images/portfolio/smash-clara-2.jpg": [
    800,
    1200,
    1600
  ],
  "/images/portfolio/smash-clara.jpg": [
    800,
    1200,
    1200
  ],
  "/images/portfolio/smash-daryna.jpg": [
    800,
    1200,
    1600
  ],
  "/images/portfolio/smash-featured.jpg": [
    800,
    1200,
    1600
  ],
  "/images/portfolio/smash-laura-2.jpg": [
    800,
    1200,
    1600
  ],
  "/images/portfolio/smash-madalena.jpg": [
    800,
    1200,
    1200
  ],
  "/images/portfolio/smash-nazar-1.jpg": [
    800,
    1200,
    1600
  ],
  "/images/portfolio/smash-nazar-2.jpg": [
    800,
    1200,
    1600
  ],
  "/images/portfolio/studio-a.jpg": [
    800,
    1200,
    1350
  ],
  "/images/portfolio/studio-b.jpg": [
    800,
    1200,
    1350
  ],
  "/images/portfolio/studio-c.jpg": [
    800,
    1200,
    1350
  ],
  "/images/portfolio/studio-espaco.jpg": [
    800,
    1200,
    1600
  ],
  "/images/portfolio/studio-natal.jpg": [
    800,
    1200,
    1200
  ]
};
