"""
Generates responsive WebP variants for the bundled photos in packages/web/public/images:
  foo.jpg -> foo-800.webp, foo-1600.webp (never wider than the original)
and writes packages/web/src/web/lib/image-widths.ts with each source's widths,
so srcset descriptors are exact. Re-run after adding photos:
  python3 tools/optimize-images.py   (needs Pillow)
"""
import json, pathlib
from PIL import Image

ROOT = pathlib.Path(__file__).resolve().parent.parent / "packages/web"
PUBLIC = ROOT / "public"
widths = {}
for path in sorted((PUBLIC / "images").rglob("*")):
    if path.suffix.lower() not in {".jpg", ".jpeg"}:
        continue
    im = Image.open(path)
    im = im.convert("RGB")
    entry = []
    for target in (800, 1600):
        w = min(target, im.width)
        out = path.with_name(f"{path.stem}-{target}.webp")
        if not out.exists() or out.stat().st_mtime < path.stat().st_mtime:
            h = round(im.height * w / im.width)
            im.resize((w, h), Image.LANCZOS).save(out, "WEBP", quality=78, method=6)
        entry.append(w)
    widths["/" + str(path.relative_to(PUBLIC))] = entry

# Logo and footer wash: shown small / soft, shipped far too large.
logo = PUBLIC / "images/logo.png"
im = Image.open(logo)
if im.width > 640:
    im.resize((640, round(im.height * 640 / im.width)), Image.LANCZOS).save(logo, optimize=True)
wash = PUBLIC / "images/aguarela-footer.png"
Image.open(wash).save(wash.with_suffix(".webp"), "WEBP", quality=80, method=6)

out = ROOT / "src/web/lib/image-widths.ts"
out.write_text(
    "// Generated by tools/optimize-images.py — do not edit by hand.\n"
    "// Widths of the -800 and -1600 WebP variants for each bundled photo.\n"
    "export const IMAGE_WIDTHS: Record<string, [number, number]> = "
    + json.dumps(widths, indent=2)
    + ";\n"
)
print(len(widths), "photos")
